import { query } from "./_generated/server";
import { v } from "convex/values";
import { PartDslSchema } from "./lib/dsl";
import { generatePartDxf } from "./lib/dxf";
import { generatePartPdf } from "./lib/pdf";
import { generateBom } from "./lib/bom";
import { buildZip, strToBytes, type ZipEntry } from "./lib/zip";

/**
 * Build an SCS-ready zip bundle for a project. Layout:
 *
 *   <project>-bundle.zip
 *     README.md             (project metadata + instructions)
 *     bom.csv               (chunk 5.3 BOM)
 *     cuts/<role>.dxf       (one DXF per sheet-metal part)
 *     drawings/<role>.pdf   (one PDF shop drawing per sheet-metal part)
 */
export const projectZip = query({
  args: { projectId: v.id("projects") },
  handler: async (ctx, { projectId }): Promise<{ filename: string; base64: string; entryCount: number; bytes: number } | null> => {
    const project = await ctx.db.get(projectId);
    if (!project) return null;

    const parts = await ctx.db
      .query("parts")
      .withIndex("by_project", q => q.eq("projectId", projectId))
      .collect();
    const interfaces = await ctx.db
      .query("interfaces")
      .withIndex("by_project", q => q.eq("projectId", projectId))
      .collect();
    const assemblyParts = await ctx.db
      .query("assemblyParts")
      .withIndex("by_project", q => q.eq("projectId", projectId))
      .collect();

    const entries: ZipEntry[] = [];
    const sheetMetalRoles: string[] = [];

    for (const p of parts) {
      if ((p.kind ?? "sheet_metal") !== "sheet_metal" || !p.dslJson) continue;
      const parsed = PartDslSchema.safeParse(JSON.parse(p.dslJson));
      if (!parsed.success) continue;
      const safeRole = (p.role || "part").replace(/[^a-zA-Z0-9_-]/g, "_");
      sheetMetalRoles.push(p.role);
      entries.push({ path: `cuts/${safeRole}.dxf`, data: strToBytes(generatePartDxf(parsed.data)) });
      entries.push({ path: `drawings/${safeRole}.pdf`, data: generatePartPdf(parsed.data, p.label, p.role) });
    }

    const bomCsv = generateBom({
      projectName: project.name,
      parts, interfaces, assemblyParts,
    });
    entries.push({ path: "bom.csv", data: strToBytes(bomCsv) });

    const readme = [
      `# ${project.name}`,
      "",
      `Generated by Fabware on ${new Date().toISOString()}.`,
      "",
      "## Contents",
      `- \`cuts/*.dxf\` — laser-cut flat patterns, one per sheet-metal part.`,
      `  Layers: CUT (red) for outline + slots, HOLE (yellow) for drill points,`,
      `  BEND (cyan) for fold tangent lines (informational).`,
      `- \`drawings/*.pdf\` — shop drawings with title block + dimensions.`,
      `- \`bom.csv\` — Bill of Materials. Sheet-metal grouped by`,
      `  (material, thickness); hardware aggregated by McMaster part number.`,
      "",
      "## Parts",
      ...sheetMetalRoles.map(r => `- ${r}`),
      "",
      "## Submitting to Send Cut Send",
      "",
      "1. Sign in at sendcutsend.com.",
      "2. Upload each `cuts/*.dxf` individually (SCS handles one part per upload).",
      "3. Set the material + thickness from the corresponding row in `bom.csv`.",
      "4. Hand-source the McMaster hardware listed in `bom.csv` (Fabware",
      "   doesn't auto-order from McMaster yet).",
      "",
      "## Caveats",
      "",
      "- Cost figures in the BOM are first-pass estimates (±30%). Always",
      "  confirm with the actual SCS quote before ordering.",
      "- Bend lines are informational only — SCS bends per the part's",
      "  flat-pattern geometry plus the bend angles in your quote.",
      "",
    ].join("\n");
    entries.push({ path: "README.md", data: strToBytes(readme) });

    const zipBytes = buildZip(entries);
    let bin = "";
    for (let i = 0; i < zipBytes.length; i++) bin += String.fromCharCode(zipBytes[i]);
    const base64 = btoa(bin);
    const safeName = project.name.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 32) || "project";
    return {
      filename: `${safeName}-bundle.zip`,
      base64,
      entryCount: entries.length,
      bytes: zipBytes.length,
    };
  },
});
