// convex/cad/codegen/compileAssembly.ts
import type { CadIr, PartId, InlinePartRef, ExternalPartRef } from "../ir/types";
import { resolveIr } from "../resolve/resolveIr";
import { compileToBuild123d } from "./compileToBuild123d";

/**
 * Sanitize a string for use as a filename component: replace spaces and slashes
 * with underscores. Other characters are left as-is.
 */
function sanitizeForFilename(s: string): string {
  return s.replace(/[ /]/g, "_");
}

/**
 * Emit a build123d Python script that imports and positions an external STEP file.
 *
 * Convention: the sandbox mounts STEP files at /in/external/<vendor>__<partNumber>.step.
 * Phase 18 does not implement STEP fetching — the codegen just emits the expected path.
 *
 * Origin and rotation come from the ExternalPartRef (Phase 9 fields).
 * Rotation is in degrees in the IR; build123d's Location wants radians.
 */
function emitImportStep(partRef: ExternalPartRef): string {
  const vendor = sanitizeForFilename(partRef.vendor);
  const partNumber = sanitizeForFilename(partRef.partNumber);
  const stepPath = `/in/external/${vendor}__${partNumber}.step`;

  const origin = partRef.origin ?? { x: 0, y: 0, z: 0 };
  const rotation = partRef.rotation ?? { rx: 0, ry: 0, rz: 0 };

  // Cast ParamRef to number (Phase 18 scope: numeric values only — expressions treated as 0)
  const x = typeof origin.x === "number" ? origin.x : 0;
  const y = typeof origin.y === "number" ? origin.y : 0;
  const z = typeof origin.z === "number" ? origin.z : 0;

  // Rotation in degrees → radians for build123d Location
  const DEG2RAD = Math.PI / 180;
  const rx = (typeof rotation.rx === "number" ? rotation.rx : 0) * DEG2RAD;
  const ry = (typeof rotation.ry === "number" ? rotation.ry : 0) * DEG2RAD;
  const rz = (typeof rotation.rz === "number" ? rotation.rz : 0) * DEG2RAD;

  return [
    `# generated by compileAssembly — external part import for ${partRef.id}`,
    `from build123d import *`,
    `imported = import_step("${stepPath}")`,
    `positioned = imported.moved(Location((${x}, ${y}, ${z}), (${rx}, ${ry}, ${rz})))`,
    `export_step(positioned, "/out/${partRef.id}.step")`,
    `export_stl(positioned, "/out/${partRef.id}.stl")`,
  ].join("\n");
}

/**
 * Compile a multi-part assembly IR into per-part build123d Python scripts.
 *
 * For each inline part in `ir.parts`, resolves the part's inline CadIr and
 * compiles it to a build123d Python script.
 *
 * Phase 18: external parts WITH a `stepUrl` now produce an import_step script
 * that positions the STEP file in the assembly frame. External parts WITHOUT
 * a `stepUrl` are still skipped (no geometry to compile).
 *
 * Returns a map of part id → Python script string.
 *
 * If `ir.parts` is undefined (single-part IR), returns an empty object.
 * Existing callers that work with single-part IRs continue to use
 * `compileToBuild123d(resolveIr(ir))` directly.
 */
export function compileAssembly(ir: CadIr): Record<PartId, string> {
  if (!ir.parts) return {};

  const result: Record<PartId, string> = {};
  for (const [partId, partRef] of Object.entries(ir.parts)) {
    if ("kind" in partRef && partRef.kind === "external") {
      const ext = partRef as ExternalPartRef;
      if (ext.stepUrl) {
        // Phase 18: emit import_step script for externals with a STEP URL
        result[partId] = emitImportStep(ext);
      }
      // No stepUrl → skip as before (BOM-only part)
      continue;
    }
    const inline = partRef as InlinePartRef;
    const resolved = resolveIr(inline.ir as CadIr);
    result[partId] = compileToBuild123d(resolved);
  }
  return result;
}
