// Vercel Function wrapping the Fabware Express app. Any request to /api/*
// hits this handler, which hands it to the Express router defined in the
// api-server package. We import the pre-built ESM bundle (dist/app.mjs)
// rather than the TypeScript source so that Vercel's strict @vercel/node
// TypeScript config (node16 resolution) doesn't fight with our bundler-
// resolution monorepo.

import type { IncomingMessage, ServerResponse } from "node:http";
// @ts-expect-error — .mjs bundle generated by api-server's build step
import app from "../artifacts/api-server/dist/app.mjs";

// The AI designer agent loop can take 15–25s to finish; give it room.
export const config = {
  maxDuration: 60,
};

type Callable = (req: IncomingMessage, res: ServerResponse) => void;

export default function handler(req: IncomingMessage, res: ServerResponse) {
  (app as Callable)(req, res);
}
