// Vercel Function wrapping the Fabware Express app. Any request to /api/*
// hits this handler, which hands it to the Express router defined in the
// api-server package. We import the pre-built ESM bundle (dist/app.mjs)
// via dynamic import because Vercel's Node builder compiles this file to
// CommonJS, and CJS can't require() an ESM module synchronously.

let cachedApp: ((req: unknown, res: unknown) => void) | null = null;

async function getApp() {
  if (cachedApp) return cachedApp;
  // @ts-expect-error — .mjs bundle generated by api-server's build step
  const mod = await import("../artifacts/api-server/dist/app.mjs");
  cachedApp = (mod.default ?? mod) as (req: unknown, res: unknown) => void;
  return cachedApp;
}

// The AI designer agent loop can take 15–25s to finish; give it room.
export const config = {
  maxDuration: 60,
};

export default async function handler(req: unknown, res: unknown): Promise<void> {
  const app = await getApp();
  app(req, res);
}
